#!/bin/bash

awk '
BEGIN {
    if (col != 0)
    {
        col -= 1
    }
}

{
    split($0, line, " ")
    val = line[col]

    if (val ~ /[a-zA-Z]/)
    {
        total += 1
        map[val] += 1
    }
}

END {
    for (i in map)
    {
        printf("%s %f\n", i, map[i] / total * 100)
    }
}
' col=$1 | sort -rk2 | paste -d' ' - freq

