#!/bin/awk -f

{
    if ($1 != "")
    {
        printf("else if (item == \"%s\") { printf(\"%s\") }\n", $1, $3)
        printf("else if (item == \"%s\") { printf(\"%s\") }\n", tolower($1), tolower($3))
    }
}
