#!/bin/awk -f

BEGIN {
    if (cols == 0)
    {
        cols = 1
    }
}

{
    split($0, chars, "")
    for (i = 1; i <= length($0); i++)
    {
        if (chars[i] ~ /[a-zA-Z]/)
        {
            printf("%s", toupper(chars[i]))

            total++
            if (total == cols)
            {
                total = 0
                printf("\n")
            }
            else
            {
                printf(" ")
            }
        }
    }
}
