#!/bin/bash

vals=$(cat txt1 | tr '\n' ' ' | ./clean_and_split -v cols=$1)

i=0
while ! test $i -eq $1
do
    i=$(expr $i + 1)

    replace=$(echo "$vals" | ./freq_analyse $i | ./replace)

    awk_script="$awk_script
        item = \$$i
        if (item ~ /[^a-zA-Z]/) { printf(\"%s\", item) }
        $replace"
done

echo "$vals" | awk "
{
    $awk_script
}"
