#!/bin/php
<?php

$file = $argv[1];

$message = file_get_contents($file);
$cipher  = preg_replace('/[^a-zA-Z]/', '', $message);

$i = $mode = -1;
while (++$i < strlen($message))
{
    if (ctype_alpha($message{$i}))
    {
        switch (++$mode % 3)
        {
            case 0:
                echo shift($message{$i}, -22);
                break;
            case 1:
                echo shift($message{$i}, -4);
                break;
            case 2:
                echo shift($message{$i}, -17);
                break;
        }
    }
    else
    {
        echo $message{$i};
    }
}

function shift($char, $shift)
{
    $char = ord($char);
    $new  = $char + $shift;

    if ($char < 90)
    {
        if     ($new < 65) $new += 26;
        elseif ($new > 90) $new -= 26;
    }
    else
    {
        if     ($new < 97)  $new += 26;
        elseif ($new > 122) $new -= 26;
    }

    return chr($new);
}
