#!/bin/awk -f

{
    split($0, text, "")
    mode = 0
    pt = ""

    for (i=1; i <= length($0); i++)
    {
        if (!(text[i] ~ /[a-zA-Z]/))
        {
            printf text[i]
        }
        else
        {
            if (mode % 2 == 0)
            {
                switch (text[i])
                {
                    case "e":
                        printf "a"
                        break
                    default:
                        printf "1"
                }
            }
            else
            {
                switch (text[i])
                {
                    case "r":
                        printf"a"
                        break
                    case "j":
                        printf"e"
                        break
                    default:
                        printf "2"
                }
            }

            mode++
        }
    }
}
